CREATE TABLE IF NOT EXISTS tl_person(
  pid INT PRIMARY KEY,
  name VARCHAR(255) DEFAULT '',
  age int DEFAULT 10
);

CREATE TABLE IF NOT EXISTS tl_newinfo(
  nid INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(300) DEFAULT '',
  content VARCHAR(5000) DEFAULT ''
);
